# Generated by Django 3.2.8 on 2023-10-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231006_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phoneNumber', models.CharField(max_length=100, verbose_name='Name')),
                ('emailAddress', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'WebsiteContent',
                'verbose_name_plural': 'WebsiteContents',
            },
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
