# Generated by Django 3.2.8 on 2023-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231017_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontent',
            name='phoneNumber',
            field=models.CharField(max_length=100, verbose_name='Phone Number'),
        ),
    ]
