# Generated by Django 3.2.8 on 2023-10-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_websitesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteSetting',
        ),
    ]
