# Generated by Django 3.2.8 on 2023-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_websitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactprofile',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
