# Generated by Django 3.2.8 on 2023-10-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contactprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='websiteURL',
            field=models.CharField(default='None', max_length=200, verbose_name='Website URL'),
        ),
    ]
